### ISSUE TITLE
Add URLs to all the empty links in `README.md`

### ISSUE THREAD

**Issue by Agent-E11** [Agent-E11/basic-discord-bot#2]

**Comment by 20leva** [comment]
what link to put for Python script? some package or

**Comment by 20leva** [comment]
idk also what to put in "save the bot's token", "make a Discord guild" and "save its ID"

**Comment by Agent-E11** [comment]
The "Python Script" and "Docker" links go to different sections in `README.md`. Most of the other links go to tutorials on how to do the thing described in the text of the link (preferably, a tutorial from the [`discord.py` documentation](https://discordpy.readthedocs.io/), or other official places, the [Docker documentation](https://docs.docker.com/) for instance). I have finished adding URLs in the most recent commit.
